create table tb_persons (
                            person_age integer,
                            person_id bigint generated by default as identity,
                            tasks_id bigint,
                            person_email varchar(255) unique,
                            person_name varchar(255),
                            primary key (person_id)
);

create table tb_tasks (
                          task_id bigint generated by default as identity,
                          task_difficulty varchar(255),
                          task_name varchar(255),
                          primary key (task_id)
);

alter table if exists tb_persons
    add constraint FKns0ch9q0j35hqjro9glge42g4
    foreign key (tasks_id)
    references tb_tasks(task_id);